volumes:
  postgres_volume:

services:
  pg-local:
    image: postgres:17.4-alpine3.21
    env_file:
      - "config/local.env"
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
